steps:
  # Step 1: Check/create Artifact Registry
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if ! gcloud artifacts repositories describe vamsi-artifact-repo --location=us-central1 --project=thematic-land-477215-a5; then
          echo "Repository doesn't exist. Creating now."
          gcloud artifacts repositories create vamsi-artifact-repo --repository-format=docker --location=us-central1 --project=thematic-land-477215-a5
        else
          echo "Repository already exists."
        fi

  # Step 2: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/thematic-land-477215-a5/vamsi-artifact-repo/my-app:latest', '.']

  # Step 3: Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/thematic-land-477215-a5/vamsi-artifact-repo/my-app:latest']



images:
  - 'us-central1-docker.pkg.dev/thematic-land-477215-a5/vamsi-artifact-repo/my-app:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  pool:
    name: 'projects/thematic-land-477215-a5/locations/us-central1/workerPools/wp'
  dynamic_substitutions: true
