steps:
  # Step 1: Create Artifact Registry if not exists
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        # Check if the Artifact Registry exists
        if ! gcloud artifacts repositories describe vamsi-artifact-repo --location=asia-east1 --project=enhub-cloud-interns; then
          echo "Artifact Registry doesn't exist. Creating it now."
          gcloud artifacts repositories create vamsi-artifact-repo --repository-format=docker --location=asia-east1 --project=enhub-cloud-interns
        else
          echo "Artifact Registry already exists."
        fi

  # Step 2: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-east1-docker.pkg.dev/enhub-cloud-interns/vamsi-artifact-repo/my-app:latest', '.']
    # Ensure Docker build step is successful
    id: 'docker-build'
    waitFor: ['-']

  # Step 3: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-east1-docker.pkg.dev/enhub-cloud-interns/vamsi-artifact-repo/my-app:latest']
    id: 'docker-push'
    waitFor: ['docker-build']

  # Step 4: Create or update secret in Secret Manager
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        echo '{"db_user":"vamsi","db_pass":"securepassword123","api_key":"your-api-key-value"}' > secret.json
        if gcloud secrets describe my-app-secret --project=enhub-cloud-interns >/dev/null 2>&1; then
          gcloud secrets versions add my-app-secret --data-file=secret.json --project=enhub-cloud-interns
        else
          gcloud secrets create my-app-secret --data-file=secret.json --replication-policy=automatic --project=enhub-cloud-interns
        fi
    id: 'secret-manager'
    waitFor: ['docker-push']

images:
  - asia-east1-docker.pkg.dev/enhub-cloud-interns/vamsi-artifact-repo/my-app:latest

options:
  logging: CLOUD_LOGGING_ONLY
