steps:
  # Step 1: Check/create Artifact Registry
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if ! gcloud artifacts repositories describe vamsi-artifact-repo --location=asia-east1 --project=enhub-cloud-interns; then
          echo "Repository doesn't exist. Creating now."
          gcloud artifacts repositories create vamsi-artifact-repo --repository-format=docker --location=asia-east1 --project=enhub-cloud-interns
        else
          echo "Repository already exists."
        fi

  # Step 2: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-east1-docker.pkg.dev/enhub-cloud-interns/vamsi-artifact-repo/my-app:latest', '.']

  # Step 3: Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-east1-docker.pkg.dev/enhub-cloud-interns/vamsi-artifact-repo/my-app:latest']

  # Step 4: Delete existing VM
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Deleting VM if it exists..."
        gcloud compute instances delete my-vm-instance --zone=asia-east1-b --quiet || true

  # Step 5: Create VM
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - compute
      - instances
      - create
      - my-vm-instance
      - --zone=asia-east1-b
      - --machine-type=e2-micro
      - --image-family=debian-11
      - --image-project=debian-cloud
      - --boot-disk-size=10GB
      - --tags=http-server,https-server
      - --scopes=https://www.googleapis.com/auth/cloud-platform
      - --service-account=1064351983714-compute@developer.gserviceaccount.com
      - --project=enhub-cloud-interns

  # Step 6: Sleep and Install Docker
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Sleeping for 90s to let SSH key propagate..."
        sleep 90
        gcloud compute ssh my-vm-instance --zone=asia-east1-b --project=enhub-cloud-interns --command="\
          sudo apt-get update && \
          sudo apt-get install -y docker.io && \
          sudo systemctl start docker"

  # Step 7: Pull, save, and SCP the Docker image to VM
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Preparing Docker image to copy..."
        docker pull asia-east1-docker.pkg.dev/enhub-cloud-interns/vamsi-artifact-repo/my-app:latest
        docker save -o my-app.tar asia-east1-docker.pkg.dev/enhub-cloud-interns/vamsi-artifact-repo/my-app:latest
        sleep 30
        gcloud compute scp my-app.tar my-vm-instance:~ --zone=asia-east1-b --project=enhub-cloud-interns

  # Step 8: Load image and run container
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sleep 30
        gcloud compute ssh my-vm-instance --zone=asia-east1-b --project=enhub-cloud-interns --command="\
          sudo docker load -i my-app.tar && \
          sudo docker run -d -p 8080:8080 asia-east1-docker.pkg.dev/enhub-cloud-interns/vamsi-artifact-repo/my-app:latest"

  # Step 9: Verify app and fetch secret
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sleep 30
        echo "Checking if application is running..."
        if gcloud compute ssh my-vm-instance --zone=asia-east1-b --project=enhub-cloud-interns --command='curl -s http://localhost:8080' &>/dev/null; then
          echo "Application is running. Fetching secret..."
          gcloud compute ssh my-vm-instance --zone=asia-east1-b --project=enhub-cloud-interns --command='gcloud secrets versions access latest --secret=my-app-secret --project=enhub-cloud-interns'
        else
          echo "Application is NOT running."
        fi

images:
  - 'asia-east1-docker.pkg.dev/enhub-cloud-interns/vamsi-artifact-repo/my-app:latest'

options:
  logging: CLOUD_LOGGING_ONLY
