steps:
  # Step 1: Check/create Artifact Registry
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if ! gcloud artifacts repositories describe vamsi-artifact-repo --location=asia-east1 --project=crested-polygon-472204-n5; then
          echo "Repository doesn't exist. Creating now."
          gcloud artifacts repositories create vamsi-artifact-repo --repository-format=docker --location=asia-east1 --project=crested-polygon-472204-n5
        else
          echo "Repository already exists."
        fi

  # Step 2: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-east1-docker.pkg.dev/crested-polygon-472204-n5/vamsi-artifact-repo/my-app:latest', '.']

  # Step 3: Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-east1-docker.pkg.dev/crested-polygon-472204-n5/vamsi-artifact-repo/my-app:latest']



images:
  - 'asia-east1-docker.pkg.dev/crested-polygon-472204-n5/vamsi-artifact-repo/my-app:latest'

options:
  logging: CLOUD_LOGGING_ONLY
